Added /usersearch and /useractivity methods
crookedneighbor/amplitude pull request #24
Opened 2016-11-13 06:27 UTC by geoffdutton

Wrappers around these:

https://amplitude.zendesk.com/hc/en-us/articles/205469748-Dashboard-Rest-API-Export-Amplitude-Dashboard-Data#user%20search

https://amplitude.zendesk.com/hc/en-us/articles/205469748-Dashboard-Rest-API-Export-Amplitude-Dashboard-Data#user-activity

2016-11-13 13:42 UTC, crookedneighbor requested changes
Left some comments, but looks mostly good to me.

2016-11-13 13:42 UTC, crookedneighbor commented on .gitignore
> +.idea
Please remove this.

2016-11-13 13:42 UTC, crookedneighbor commented on README.md
> +The export method requires your [secret key](https://amplitude.zendesk.com/hc/en-us/articles/206728448-Where-can-I-find-my-app-s-API-Key-or-Secret-Key-) to be added when initializing the amplitude ob
export method -> user activity method

2016-11-13 13:42 UTC, crookedneighbor commented on amplitude.js
> +    throw new Error('amplitude_id for must be passed.')
This sentence does not make grammatic sense.

2016-11-13 13:42 UTC, crookedneighbor commented on amplitude.js
> +    throw new Error('secretKey must be set to use the export method')
Export method referenced here.

2016-11-13 13:42 UTC, crookedneighbor commented on amplitude.js
> +    throw new Error('secretKey must be set to use the export method')
Export method.

2016-11-13 13:42 UTC, crookedneighbor commented on test/userSearch.test.js
> +
Why so many blank spaces?

2016-11-13 13:42 UTC, crookedneighbor commented on test/userSearch.test.js
> +    userActivityStub = sinon.stub(this.amplitude, 'userActivity')
Let's use `this.userActivityStub` instead

2016-11-13 13:42 UTC, crookedneighbor commented on test/userSearch.test.js
> +
Extra line break here.

2016-11-13 13:42 UTC, crookedneighbor commented on test/userSearch.test.js
> +      console.error(err)
Remove this.

2016-11-13 13:42 UTC, crookedneighbor commented on test/userSearch.test.js
> +      console.error(err)
Remove this.

2016-11-13 13:42 UTC, crookedneighbor commented on test/userSearch.test.js
> +      console.error(err)
Remove.

2016-11-13 13:42 UTC, crookedneighbor commented on test/userSearch.test.js
> +      console.error(err)
Remove.

2016-11-13 13:42 UTC, crookedneighbor commented on amplitude.js
> +
Extra line break.

2016-11-13 13:42 UTC, crookedneighbor commented on amplitude.js
> +  .query({
This should be indebted to match the style of the other methods.

2016-11-13 13:42 UTC, crookedneighbor commented on amplitude.js
> +
Extra line break.

2016-11-13 13:42 UTC, crookedneighbor commented on README.md
> +amplitude.userActivity('amplitude_id')
Let's include how it resolves and provide something some examples for the properties returned.

2016-11-13 13:42 UTC, crookedneighbor commented on README.md
> +amplitude.userSearch('some-id-or-user-prop')
Let's include how it resolves and provide something some examples for the properties returned.

2016-11-13 20:59 UTC, geoffdutton commented on .gitignore
> +.idea
Do you want the .idea folder to be committed in the repo? It's the folder generated by the Intellij IDEA IDE.

2016-11-13 20:59 UTC, geoffdutton commented
I've addressed the your comments. Thanks for reviewing.

2016-11-13 22:38 UTC, crookedneighbor commented on .gitignore
> +.idea
No. you should have the .idea folder as an part of your global gitignore. Not part of this repo.

2016-11-14 00:07 UTC, geoffdutton commented
Ah, got it.

> On Nov 13, 2016, at 4:38 PM, Blade Barringer <notifications@github.com> wrote:
> 
> @crookedneighbor commented on this pull request.
> 
> In .gitignore:
> 
> > @@ -1 +1,2 @@
>  node_modules/
> +.idea
> No. you should have the .idea folder as an part of your global gitignore. Not part of this repo.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
>

2016-11-14 16:34 UTC, geoffdutton commented on README.md
> +amplitude.userSearch('some-id-or-user-prop')
Are the examples I added what you were looking for?

2016-11-17 03:24 UTC, closed without merging

2016-11-17 03:29 UTC, crookedneighbor commented
Made a few changes and took out the `withUserActivity` shortcut in the `userSearch` method, but added an example in the readme for how to do it yourself. I think it might make more sense to have a separate method that calls both methods internally, but I want to sit on it a bit before committing to that being a part of the modules API.

How do you want to be credited? I need your preferred name, email and website url. If I don't hear from you in the next few days, I'll just use what's on your git commit.

```json
{
  "name": "Geoff Dutton",
  "email": "g.dutton@gmail.com"
}
```

2016-11-22 20:31 UTC, geoffdutton commented
Sorry, I missed this. That's fine for credit, thank you.

And yes, I was going back and fourth on the `withUserActivity`. It's not part of the amplitude api spec, the main reason I added it is because I have a bunch of spots in some of my production apps that I have been using it.

I'm fine with leaving it out though.

2017-01-03 23:29 UTC, crookedneighbor commented
Sorry for the delay on this. The latest release has your changes. Thanks for the work!