Allow passing of sessionId in camel case, optionally in constructor opts
crookedneighbor/amplitude pull request #44
Opened 2017-04-21 15:57 UTC by chase-seibert

Previously, passing sessionId would not pass the correct snake case
value to Amplitude. Because this value may not change over the life of
your amplitude client, allow passing as a constructor option.

2017-04-21 16:03 UTC, crookedneighbor commented
I corrected a typo you had. Please add a test in this file for this behavior: https://github.com/crookedneighbor/amplitude/blob/master/test/initialize.test.js

2017-04-21 16:39 UTC, chase-seibert commented
Added tests.

2017-04-21 16:45 UTC, crookedneighbor commented
Awesome, could you add some documentation for this in the README?

Also, if desired, add yourself to the contributors array in the package.json https://github.com/crookedneighbor/amplitude/blob/b53f98ff6a454b2a69418059d34a8ba8b2247271/package.json#L9

2017-04-21 16:58 UTC, chase-seibert commented
Updated docs.

2017-04-21 17:00 UTC, crookedneighbor requested changes

2017-04-21 17:00 UTC, crookedneighbor commented on README.md
> +deviceId -> session_id
deviceId should be sessionId

2017-04-21 17:00 UTC, crookedneighbor commented on README.md
>  ### User/Device ID
This heading should be updated.

2017-04-21 17:00 UTC, crookedneighbor commented on package.json
> +    },
Trailing commas are not valid JSON.

2017-04-21 17:01 UTC, crookedneighbor commented
Just a few things to fix and I think it's good to go.

2017-04-21 18:06 UTC, chase-seibert commented
All set.

2017-04-24 12:15 UTC, merged

2017-04-24 12:20 UTC, crookedneighbor commented
Thanks for this. Version 3.5.0 includes this feature.